version: "3.7"

services:
  viz:
    image: bretfisher/visualizer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8086:8080"
    deploy:
      placement:
        constraints:
          - node.role == manager
  firefly:
    image: bretfisher/browncoat:v1
    deploy:
      placement:
        constraints:
          - node.hostname == node1
      replicas: 5
    ports:
      - "80:80"
    environment:
      - "DEPLAY_STARTUP:5000"
    networks:
      - "verse"

networks:
  verse:
    driver: overlay
    attachable: true
