version: "3.7"

services:
  firefly:
    image: bretfisher/browncoat:v1
    deploy:
      placement:
        constraints:
          - node.role == node1
      replicas: 5
    ports:
      - "80:80"
    networks:
      - "verse"

networks:
  verse:
    driver: overlay
